### ISSUE TITLE
Bug in Get Started pages...

### ISSUE THREAD

**Issue by GaTechThomas** [SteeltoeOSS/MainSite#58]
In the following two lines of code, the command runs on port 80, but the link is for port 8080, which (of course) fails. Need to use either 80 or 8080 in both places.

https://github.com/SteeltoeOSS/MainSite/blob/58c6cc3ab310c7ea7296a61caa6dc19fe18e4a2b/src/Client/Components/RunAppTab/Docker.razor#L29

https://github.com/SteeltoeOSS/MainSite/blob/58c6cc3ab310c7ea7296a61caa6dc19fe18e4a2b/src/Client/Components/RunAppTab/Kubernetes.razor#L27

**Comment by jkonicki** [comment]
@kenswan Worth verifying this is fixed in new guides

**Comment by bart-vmware** [comment]
From what I found, `MainSite/src/Client/Components/RunAppTab/Docker.razor` is not referenced from anywhere in the current version of the main branch. There are usages of `MainSite/src/Client/Components/RunAppTab/Kubernetes.razor`, but I was unable to navigate there by clicking through the website. I traced this down to https://github.com/SteeltoeOSS/MainSite/commit/316e0cf74ed74bba8df9261a0856e1ff5df2e200#diff-831fb3622e44fced9d46e525117a016a0a5dbd9d6e31dc989781e83150f79e30R23-R28, where the link to the tutorials was commented out. After re-activating that, the guides become accessible again.

While it is still possible to navigate to these tutorials directly if you know their URLs (for example, https://steeltoe.io/app-configuration/get-started/placeholder), the fact that they are hidden today makes me think these tutorials have become obsolete. They refer to Steeltoe 2.4 using .NET Core 3.1. I suspect these tutorials are superseded by the ones at https://docs.steeltoe.io/guides/, whose sources are in the https://github.com/SteeltoeOSS/Documentation repository. Therefore I believe this issue no longer applies and can be closed.

@jkonicki can you confirm this?

**Comment by bart-vmware** [comment]
At https://docs.steeltoe.io, the only references I found by searching for 80:80 are these:
- https://docs.steeltoe.io/api/v3/management/springbootadmin.html
  ```
  docker run -d -p 8080:8080 steeltoeoss/spring-boot-admin
  ```
- https://docs.steeltoe.io/guides/security/sso-openid-netcore.html?tabs=cli
  ```
  docker run --rm -ti -p 8080:8080 --name steeltoe-uaa steeltoeoss/workshop-uaa-server
  ```

**Comment by jkonicki** [comment]
@bart-vmware There are a couple reasons here:  
1) There was talk of removing all the Razor pages and all of the Razor content as time permitted, since it really doesn't provide much anymore.  
2)The original Getting started tutorials were obsolete and in order to remove most of the confusion we redirected many of the links directly to our docs.  
3) The reason the old Razor pages were left, was because the next effort was to add forwarding of those Razor pages to the docs for those who had direct links or found them via search engine.  As you can see, that was not done.  A ticket should be open for the forwarding and removal of the old Razor pages, if it hasn't already.

**Comment by bart-vmware** [comment]
Thanks for the clarification. I've created #107 to track this.
